### ISSUE TITLE
Clean up Order Flow UI

### ISSUE THREAD

**Issue by irab** [coshopnz/nextjs-starter-medusa#3]
Remove Delivery component and ensure order step through flow is working

**Comment by mandyh101** [comment]
1. checkout?step=address
docs.medisa.js.com/references/entities/classes/Address
- can we edit the personal details form to first name, last name, phone number, email

Test the flow
- do you receive an email confirmation
- do the emails prompt an account creation - if yes, can we edit that out?
- does the order summary break if we remove fields from personal details?

2. checkout?step=delivery
- can we skip this and go straight to payment

3. checkout?step=payment:
- options should be: bank transfer or credit/debit card (constants.tsx is where they can be edited)
- if cc is selected a stripe follow is triggered beneath for payment
- if bank transfer is selected the user can continue to review

4. checkout?step=review:
- why is place order button disabled
- edit content in review step if payment option is bank transfer to display instructions

**Comment by mandyh101** [comment]
Quick update on order workflow progress:

1. personal details section - done
- all fields not required have been edited out
- limited the options in the dropdown select to be NZ only
- updated button copy to proceed to payment instead of delivery

2. Delivery section - wip
- we were skipping this section but I have brought it back so that we can define a shipping option as the checkout workflow cannot complete without a shipping method option provided
- note that I created a shipping option in the admin UI called pick up against the NZ region and this is set as the default option
**- I am going to try move the code that sorts the shipping option into address/personal details component or set the default shipping option by default so that users don't need to go through the delivery step and we can hide it.** 

3. Payment section - done
- edited the manual option with wording and new icon to make it clear to users they can select this for manual bank transfers

4. Review step - WIP
- fix conditional checks that were hiding the content and disabling the proceed to payment button because it was expecting data that we are no longer passing through
- tested and I can reach the order success page with both manual and stripe payment selections
- there is a default copy in this section that I still need to edit , I will look at the miro board for inspiration but if I'm not sure I will check in with the team

Other todos:
- BUG: for some reason events are being triggered multiple times across components (e.g. when I placed an order, four orders went through to the admin UI)
